name: Run Linter

on:
  workflow_call:
    inputs:
      lint_script:
        required: false
        type: string
        default: npm run lint

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - run: npm ci
      - run: ${{ inputs.lint_script }}