# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Tests

on:
  workflow_call:
    inputs:
      build_script:
        required: false
        type: string
        default: npm run build
      test_script:
        required: false
        type: string
        default: npm test
      working_directory:
        required: false
        type: string
        default: .
    secrets:
      NPM_TOKEN:
        required: false

jobs:
  tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      # Skip post-install scripts here, as a malicious
      # script could steal the NPM_TOKEN.
      - run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # `npm rebuild` will run all those post-install scripts for us.
      - run: npm rebuild
      - run: ${{ inputs.build_script }}
      - run: ${{ inputs.test_script }}
