name: WCAG tests

on:
  workflow_call:
    inputs:
      build_script:
        required: false
        type: string
        default: npm run build
      fetch_depth:
        required: false
        type: number
        default: 1
    secrets:
      NPM_TOKEN:
        required: false
      MAPBOX_API_KEY:
        required: false

jobs:
  WCAG-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ inputs.fetch_depth }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      # Skip post-install scripts here, as a malicious
      # script could steal the NPM_TOKEN.
      - run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # `npm rebuild` will run all those post-install scripts for us.
      - run: npm rebuild
      - run: ${{ inputs.build_script }}
        env:
          MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
      - run: npm run wcag
        env:
          MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
