name: WCAG tests

on:
  workflow_call:
    inputs:
      build_script:
        required: false
        type: string
        default: npm run build
    secrets:
      NPM_TOKEN:
        required: false

jobs:
  WCAG-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      # Skip post-install scripts here, as a malicious
      # script could steal the NPM_TOKEN.
      - run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # `npm rebuild` will run all those post-install scripts for us.
      - run: npm rebuild
      - run: ${{ inputs.build_script }}
      - run: npm run wcag
